#default pr_commands
# "/agentic_describe"
# "/agentic_review"

[github_app]
pr_commands = []

[review_agent]
comments_location_policy = "both"

inline_comments_severity_threshold = 1

# Extra prompt for usecase to be added as instruction for the agent
issues_user_guidelines = ""
compliance_user_guidelines = ""
