FROM devkitpro/devkitarm:20260221

LABEL org.opencontainers.image.title="ToyGine2 GBA Toolchain"
LABEL org.opencontainers.image.description="devkitARM toolchain for building ToyGine2 targeting GBA."
LABEL org.opencontainers.image.source="https://github.com/ToymanInteractive/toygine2"
LABEL org.opencontainers.image.url="https://github.com/ToymanInteractive/toygine2"
LABEL org.opencontainers.image.documentation="https://github.com/ToymanInteractive/toygine2/blob/main/README.md"
LABEL org.opencontainers.image.vendor="Toyman Interactive"
LABEL org.opencontainers.image.authors="Toyman Interactive <https://github.com/ToymanInteractive>"
LABEL org.opencontainers.image.licenses="MIT"
LABEL org.opencontainers.image.base.name="docker.io/devkitpro/devkitarm:20260221"
