var searchData=
[
  ['access_20modifiers_0',['Access Modifiers',['../df/d81/md__a_g_e_n_t_s.html#access-modifiers',1,'']]],
  ['agents_20guidelines_20for_20this_20repository_1',['AGENTS Guidelines for This Repository',['../df/d81/md__a_g_e_n_t_s.html',1,'']]],
  ['alignment_2',['Pointer and Reference Alignment',['../df/d81/md__a_g_e_n_t_s.html#pointer-and-reference-alignment',1,'']]],
  ['allocation_20rules_3',['Memory and Allocation Rules',['../df/d81/md__a_g_e_n_t_s.html#memory-and-allocation-rules',1,'']]],
  ['also_20tags_4',['See-Also Tags',['../df/d81/md__a_g_e_n_t_s.html#see-also-tags',1,'']]],
  ['and_20allocation_20rules_5',['Memory and Allocation Rules',['../df/d81/md__a_g_e_n_t_s.html#memory-and-allocation-rules',1,'']]],
  ['and_20automation_6',['Tools and Automation',['../df/d81/md__a_g_e_n_t_s.html#tools-and-automation',1,'']]],
  ['and_20delete_7',['&lt;span class=&quot;tt&quot;&gt;= default&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;= delete&lt;/span&gt;',['../df/d81/md__a_g_e_n_t_s.html#autotoc_md-default-and--delete',1,'']]],
  ['and_20documentation_8',['Comments and Documentation',['../df/d81/md__a_g_e_n_t_s.html#comments-and-documentation',1,'']]],
  ['and_20duplication_9',['Redundancy and Duplication',['../df/d81/md__a_g_e_n_t_s.html#redundancy-and-duplication',1,'']]],
  ['and_20postconditions_10',['Preconditions and Postconditions',['../df/d81/md__a_g_e_n_t_s.html#preconditions-and-postconditions',1,'']]],
  ['and_20reference_20alignment_11',['Pointer and Reference Alignment',['../df/d81/md__a_g_e_n_t_s.html#pointer-and-reference-alignment',1,'']]],
  ['and_20references_20in_20text_12',['Constants and References in Text',['../df/d81/md__a_g_e_n_t_s.html#constants-and-references-in-text',1,'']]],
  ['and_20spacing_13',['Indentation and Spacing',['../df/d81/md__a_g_e_n_t_s.html#indentation-and-spacing',1,'']]],
  ['and_20standard_14',['Language and Standard',['../df/d81/md__a_g_e_n_t_s.html#language-and-standard',1,'']]],
  ['and_20structure_15',['Test Length and Structure',['../df/d81/md__a_g_e_n_t_s.html#test-length-and-structure',1,'']]],
  ['and_20template_20code_16',['Inline and Template Code',['../df/d81/md__a_g_e_n_t_s.html#inline-and-template-code',1,'']]],
  ['and_20warnings_17',['Notes and Warnings',['../df/d81/md__a_g_e_n_t_s.html#notes-and-warnings',1,'']]],
  ['assertions_18',['Assertions',['../df/d81/md__a_g_e_n_t_s.html#assertions',1,'Assertions'],['../df/d81/md__a_g_e_n_t_s.html#value-based-assertions',1,'Value-Based Assertions']]],
  ['assertions_20including_20utf_208_19',['String length assertions (including UTF-8)',['../df/d81/md__a_g_e_n_t_s.html#string-length-assertions-including-utf-8',1,'']]],
  ['assumptions_20',['Test Framework Assumptions',['../df/d81/md__a_g_e_n_t_s.html#test-framework-assumptions',1,'']]],
  ['auto_21',['&lt;span class=&quot;tt&quot;&gt;auto&lt;/span&gt;',['../df/d81/md__a_g_e_n_t_s.html#auto',1,'']]],
  ['automation_22',['Tools and Automation',['../df/d81/md__a_g_e_n_t_s.html#tools-and-automation',1,'']]]
];
