var searchData=
[
  ['c_20compilers_0',['Supported C++ compilers',['../index.html#supported-c-compilers',1,'']]],
  ['c_20game_20engine_20style_20guide_1',['C++ game engine style guide',['../df/d81/md__a_g_e_n_t_s.html#c-game-engine-style-guide',1,'']]],
  ['c_20practices_2',['Modern C++ Practices',['../df/d81/md__a_g_e_n_t_s.html#modern-c-practices',1,'']]],
  ['characteristics_3',['Characteristics',['../df/d81/md__a_g_e_n_t_s.html#section-performance-performance-characteristics',1,'&lt;span class=&quot;tt&quot;&gt;\\section performance Performance Characteristics&lt;/span&gt;'],['../d0/d21/classtoy_1_1_string_fixed_storage.html#performance',1,'Performance Characteristics']]],
  ['checklist_4',['Documentation Pre-Commit Checklist',['../df/d81/md__a_g_e_n_t_s.html#documentation-pre-commit-checklist',1,'']]],
  ['class_5',['Class',['../df/d81/md__a_g_e_n_t_s.html#regular-class',1,'Regular Class'],['../df/d81/md__a_g_e_n_t_s.html#template-class',1,'Template Class']]],
  ['class_20documentation_20templates_6',['Class Documentation Templates',['../df/d81/md__a_g_e_n_t_s.html#class-documentation-templates',1,'']]],
  ['class_20struct_20documentation_20order_7',['Class / Struct Documentation Order',['../df/d81/md__a_g_e_n_t_s.html#class--struct-documentation-order',1,'']]],
  ['class_20without_20compatibility_8',['Simplified Class (without compatibility)',['../df/d81/md__a_g_e_n_t_s.html#simplified-class-without-compatibility',1,'']]],
  ['code_9',['Inline and Template Code',['../df/d81/md__a_g_e_n_t_s.html#inline-and-template-code',1,'']]],
  ['coding_20principles_10',['General Coding Principles',['../df/d81/md__a_g_e_n_t_s.html#general-coding-principles',1,'']]],
  ['comments_20and_20documentation_11',['Comments and Documentation',['../df/d81/md__a_g_e_n_t_s.html#comments-and-documentation',1,'']]],
  ['commit_20checklist_12',['Documentation Pre-Commit Checklist',['../df/d81/md__a_g_e_n_t_s.html#documentation-pre-commit-checklist',1,'']]],
  ['compatibility_13',['Compatibility',['../d7/d15/classtoy_1_1_o_string_stream.html#compatibility',1,'']]],
  ['compatibility_14',['Simplified Class (without compatibility)',['../df/d81/md__a_g_e_n_t_s.html#simplified-class-without-compatibility',1,'']]],
  ['compatibility_20compatibility_20optional_15',['&lt;span class=&quot;tt&quot;&gt;\\section compatibility Compatibility&lt;/span&gt; (optional)',['../df/d81/md__a_g_e_n_t_s.html#section-compatibility-compatibility-optional',1,'']]],
  ['compatibility_20optional_16',['&lt;span class=&quot;tt&quot;&gt;\\section compatibility Compatibility&lt;/span&gt; (optional)',['../df/d81/md__a_g_e_n_t_s.html#section-compatibility-compatibility-optional',1,'']]],
  ['compatible_20naming_17',['STL-Compatible Naming',['../df/d81/md__a_g_e_n_t_s.html#stl-compatible-naming',1,'']]],
  ['compile_20time_20constexpr_20tests_18',['Compile-Time (&lt;span class=&quot;tt&quot;&gt;constexpr&lt;/span&gt;) Tests',['../df/d81/md__a_g_e_n_t_s.html#compile-time-constexpr-tests',1,'']]],
  ['compile_20time_20vs_20runtime_20testing_19',['Compile-Time vs Runtime Testing',['../df/d81/md__a_g_e_n_t_s.html#compile-time-vs-runtime-testing',1,'']]],
  ['compilers_20',['Supported C++ compilers',['../index.html#supported-c-compilers',1,'']]],
  ['concept_21',['Concept',['../df/d81/md__a_g_e_n_t_s.html#concept',1,'']]],
  ['concept_20documentation_22',['Concept Documentation',['../df/d81/md__a_g_e_n_t_s.html#concept-documentation',1,'']]],
  ['const_20reference_20style_23',['Const Reference Style',['../df/d81/md__a_g_e_n_t_s.html#const-reference-style',1,'']]],
  ['constexpr_20first_20design_24',['Constexpr-First Design',['../df/d81/md__a_g_e_n_t_s.html#constexpr-first-design',1,'']]],
  ['constexpr_20runtime_20parity_25',['Constexpr + Runtime Parity',['../df/d81/md__a_g_e_n_t_s.html#constexpr--runtime-parity',1,'']]],
  ['constexpr_20tests_26',['Compile-Time (&lt;span class=&quot;tt&quot;&gt;constexpr&lt;/span&gt;) Tests',['../df/d81/md__a_g_e_n_t_s.html#compile-time-constexpr-tests',1,'']]],
  ['constructors_27',['Explicit Constructors',['../df/d81/md__a_g_e_n_t_s.html#explicit-constructors',1,'']]],
  ['context_28',['Project Context',['../df/d81/md__a_g_e_n_t_s.html#project-context',1,'']]],
  ['conventions_29',['Naming Conventions',['../df/d81/md__a_g_e_n_t_s.html#naming-conventions',1,'']]],
  ['cpp_30',['Template: implementation (&lt;span class=&quot;tt&quot;&gt;.cpp&lt;/span&gt;)',['../df/d81/md__a_g_e_n_t_s.html#template-implementation-cpp',1,'']]]
];
