ToyGine2: toy::OStringStream< StringType > Class Template Reference
toy::OStringStream< StringType > Class Template Reference
String Utilities
Template output string stream class for building strings from various data types.
Public Types
using char_type = char
Type of characters stored in the string.
using pos_type = size_t
Type of positions in the string.
Public Member Functions
constexpr OStringStream () noexcept=default
Default constructor.
template<StringLike SourceStringType>
constexpr OStringStream (const SourceStringType &string) noexcept
Constructs an OStringStream from a string-like object.
constexpr OStringStream & operator= (const OStringStream &other) noexcept=default
Copy assignment operator.
constexpr OStringStream & operator= (OStringStream &&other) noexcept=default
Move assignment operator.
constexpr void swap (OStringStream &other) noexcept
Swaps the contents of this stream with another stream.
constexpr OStringStream & operator<< (bool value) noexcept
Inserts a boolean value into the stream.
constexpr OStringStream & operator<< (int8_t value) noexcept
Inserts a signed 8-bit integer value into the stream.
constexpr OStringStream & operator<< (int16_t value) noexcept
Inserts a signed 16-bit integer value into the stream.
constexpr OStringStream & operator<< (int32_t value) noexcept
Inserts a signed 32-bit integer value into the stream.
constexpr OStringStream & operator<< (int64_t value) noexcept
Inserts a signed 64-bit integer value into the stream.
constexpr OStringStream & operator<< (uint8_t value) noexcept
Inserts an unsigned 8-bit integer value into the stream.
constexpr OStringStream & operator<< (uint16_t value) noexcept
Inserts an unsigned 16-bit integer value into the stream.
constexpr OStringStream & operator<< (uint32_t value) noexcept
Inserts an unsigned 32-bit integer value into the stream.
constexpr OStringStream & operator<< (uint64_t value) noexcept
Inserts an unsigned 64-bit integer value into the stream.
constexpr OStringStream & operator<< (float value) noexcept
Inserts a single-precision floating-point value into the stream.
constexpr OStringStream & operator<< (double value) noexcept
Inserts a double-precision floating-point value into the stream.
constexpr OStringStream & operator<< (const void *value) noexcept
Inserts a pointer value into the stream.
constexpr OStringStream & operator<< (nullptr_t) noexcept
Inserts a null pointer literal into the stream.
constexpr OStringStream & operator<< (char_type value) noexcept
Inserts a single character into the stream.
template<StringLike SourceStringType>
constexpr OStringStream & operator<< (const SourceStringType &value) noexcept
Inserts a string-like object into the stream.
constexpr OStringStream & operator<< (const char_type *value) noexcept
Inserts a C string into the stream.
constexpr const StringType & str () const noexcept
Returns a const reference to the underlying string.
template<StringLike SourceStringType>
constexpr void str (const SourceStringType &string) noexcept
Sets the content of the stream from a string-like object.
constexpr CStringView view () const noexcept
Returns a non-owning view of the underlying string.
constexpr OStringStream & put (char_type character) noexcept
Appends a single character to the end of the stream.
constexpr OStringStream & write (const char_type *string, size_t count) noexcept
Writes a specified number of characters from a buffer to the stream.
constexpr pos_type tellp () const noexcept
Returns the current write position in the stream.
constexpr int precision () const noexcept
Returns the current floating-point precision setting.
constexpr int precision (int newPrecision) noexcept
Sets the floating-point precision and returns the previous value.
template<StringLike SourceStringType>
constexpr OStringStream< StringType > & operator<< (const SourceStringType &value) noexcept
Private Attributes
StringType _string
Internal string storage for the stream content.
int _precision = 6
Floating-point precision value used for number formatting.
Detailed Description
template<typename StringType>
class toy::OStringStream< StringType >
Template output string stream class for building strings from various data types.
OStringStream is a lightweight, high-performance output stream class that provides a std::ostringstream-like interface while using a fixed-size or custom string storage type. It supports formatting and inserting various data types into a string buffer, including integers, floating-point numbers, booleans, pointers, and string-like objects.
Template Parameters
StringType The type of the underlying string storage. Must satisfy the toy::StringLike concept.
Key Features
⚙️ Zero or Minimal Dynamic Allocation: Uses the provided StringType for storage (e.g., toy::FixedString)
🔧 ConstExpr Support: Most operations can be evaluated at compile time
🛡️ Exception Safety: All operations are noexcept
🔗 STL Compatibility: Provides std::ostringstream-like interface
📝 Type Safety: Uses C++20 concepts for type safety
🎯 Precision Control: Configurable precision for floating-point formatting
Usage Example
#include "o_string_stream.hpp"
#include "fixed_string.hpp"
// Create a stream with FixedString storage
toy::OStringStream<toy::FixedString<64>> stream;
// Insert various types
stream << "Value: " << 42 << ", Pi: " << 3.14159;
stream << '!' << CStringView(" Result: ") << true;
// Get the result
const auto result = stream.str();
Note
The stream only supports appending operations. All writes go to the end of the string.
The write position always equals the size of the underlying string.
See also
toy::FixedString
toy::StringLike
toy::CStringView
Member Typedef Documentation
char_type
template<typename StringType> using toy::OStringStream< StringType >::char_type = char
Type of characters stored in the string.
pos_type
template<typename StringType> using toy::OStringStream< StringType >::pos_type = size_t
Type of positions in the string.
Constructor & Destructor Documentation
OStringStream() [1/2]
template<typename StringType> toy::OStringStream< StringType >::OStringStream () constexpr default noexcept
Default constructor.
Constructs an empty OStringStream with default-initialized string storage.
Postcondition
The stream contains an empty string.
OStringStream() [2/2]
template<typename StringType> template<StringLike SourceStringType> toy::OStringStream< StringType >::OStringStream (const SourceStringType & string) explicit constexpr noexcept
Constructs an OStringStream from a string-like object.
This constructor initializes the stream by copying the content from a string-like object.
Template Parameters
SourceStringType The type of the source string. Must satisfy the toy::StringLike concept.
Parameters
string The source string-like object to copy content from.
Precondition
The string must be valid and properly initialized.
Postcondition
The stream contains a copy of the source string content.
Note
The constructor performs a deep copy of the string content.
The source string type can be different from StringType as long as both satisfy toy::StringLike.
Member Function Documentation
operator<<() [1/17]
template<typename StringType> OStringStream< StringType > & toy::OStringStream< StringType >::operator<< (bool value) constexpr noexcept
Inserts a boolean value into the stream.
This operator converts the boolean value to its string representation and appends it to the stream. The value true is converted to the string "true", and the value false is converted to the string "false".
Parameters
value The boolean value to insert into the stream.
Returns
A reference to this OStringStream, allowing operator chaining.
Note
This operator follows the same pattern as std::ostringstream::operator<<(bool).
Postcondition
The write position is advanced by the length of the appended string (4 for "true", 5 for "false").
See also
put(char_type)
write(const char_type *, size_t)
tellp()
operator<<() [2/17]
template<typename StringType> OStringStream< StringType > & toy::OStringStream< StringType >::operator<< (char_type value) constexpr noexcept
Inserts a single character into the stream.
This operator appends the specified value character to the end of the stream. The character is added directly without any conversion or formatting.
Parameters
value The character to insert into the stream.
Returns
A reference to this OStringStream, allowing operator chaining.
Postcondition
The write position is advanced by one character.
Note
This operator follows the same pattern as std::ostringstream::operator<<(char_type).
See also
operator<<(const char_type *)
operator<<(const SourceStringType &)
put(char_type)
tellp()
operator<<() [3/17]
template<typename StringType> OStringStream< StringType > & toy::OStringStream< StringType >::operator<< (const char_type * value) constexpr noexcept
Inserts a C string into the stream.
This operator appends the content of a C string to the end of the stream. The string is copied and appended to the current stream content.
Parameters
value The C string to insert into the stream.
Returns
A reference to this OStringStream, allowing operator chaining.
Precondition
The value must not be null.
Postcondition
The write position is advanced by the length of the appended string (excluding the null terminator).
Note
This operator follows the same pattern as std::ostringstream::operator<<(const char*).
The string is appended up to but not including the null terminator.
This operator is useful for inserting C-style string literals and null-terminated character arrays.
See also
operator<<(const SourceStringType &)
operator<<(char_type)
put(char_type)
write(const char_type *, size_t)
tellp()
operator<<() [4/17]
template<typename StringType> template<StringLike SourceStringType> OStringStream & toy::OStringStream< StringType >::operator<< (const SourceStringType & value) constexpr noexcept
Inserts a string-like object into the stream.
This operator appends the content of a string-like object to the end of the stream. The string content is copied and appended to the current stream content.
Template Parameters
SourceStringType The type of the source string. Must satisfy the toy::StringLike concept.
Parameters
value The string-like object to insert into the stream.
Returns
A reference to this OStringStream, allowing operator chaining.
Precondition
The value must be valid and properly initialized.
Postcondition
The write position is advanced by the length of the appended string.
Note
This operator follows the same pattern as std::ostringstream::operator<<(const std::string&).
The source string type can be different from StringType as long as both satisfy toy::StringLike.
This operator is useful for inserting string literals, toy::FixedString objects, and other string-like types.
See also
operator<<(const char_type *)
operator<<(char_type)
put(char_type)
write(const char_type *, size_t)
tellp()
operator<<() [5/17]
template<typename StringType> template<StringLike SourceStringType> OStringStream< StringType > & toy::OStringStream< StringType >::operator<< (const SourceStringType & value) constexpr noexcept
Referenced by toy::CallbacksPool< type, allocatedSize >::CallbacksPool(), toy::CStringView::CStringView(), toy::CStringView::CStringView(), toy::FixedString< allocatedSize >::FixedString(), toy::FixedString< allocatedSize >::FixedString(), toy::FixedString< allocatedSize >::FixedString(), toy::FixedVector< type, allocatedSize >::FixedVector(), toy::FixedVector< type, allocatedSize >::FixedVector(), toy::FixedVector< type, allocatedSize >::FixedVector(), toy::FixedVector< type, allocatedSize >::FixedVector(), toy::FixedVector< type, allocatedSize >::FixedVector(), toy::FixedVector< type, allocatedSize >::FixedVector(), toy::FixedVector< type, allocatedSize >::FixedVector(), toy::FixedVector< type, allocatedSize >::FixedVector(), toy::FixedVector< type, allocatedSize >::FixedVector(), OStringStream(), toy::FixedVector< type, allocatedSize >::~FixedVector(), toy::FixedString< allocatedSize >::_append_raw(), toy::CStringView::_find_first_not_of_raw(), toy::FixedString< allocatedSize >::_find_first_not_of_raw(), toy::CStringView::_find_first_of_raw(), toy::FixedString< allocatedSize >::_find_first_of_raw(), toy::CStringView::_find_last_not_of_raw(), toy::FixedString< allocatedSize >::_find_last_not_of_raw(), toy::CStringView::_find_last_of_raw(), toy::FixedString< allocatedSize >::_find_last_of_raw(), toy::CStringView::_find_raw(), toy::FixedString< allocatedSize >::_find_raw(), toy::FixedString< allocatedSize >::_insert_raw(), toy::FixedString< allocatedSize >::_replace_raw(), toy::CStringView::_rfind_raw(), toy::FixedString< allocatedSize >::_rfind_raw(), toy::CallbacksPool< type, allocatedSize >::add(), toy::FixedString< allocatedSize >::append(), toy::FixedString< allocatedSize >::append(), toy::FixedString< allocatedSize >::append(), toy::FixedString< allocatedSize >::append(), toy::CStringView::assign(), toy::CStringView::assign(), toy::FixedString< allocatedSize >::assign(), toy::FixedString< allocatedSize >::assign(), toy::FixedString< allocatedSize >::assign(), toy::FixedString< allocatedSize >::assign(), toy::FixedVector< type, allocatedSize >::assign(), toy::FixedVector< type, allocatedSize >::assign(), toy::FixedVector< type, allocatedSize >::assign(), toy::CStringView::at(), toy::FixedString< allocatedSize >::at(), toy::FixedString< allocatedSize >::at(), toy::FixedVector< type, allocatedSize >::at(), toy::FixedVector< type, allocatedSize >::at(), toy::CStringView::back(), toy::FixedString< allocatedSize >::back(), toy::FixedString< allocatedSize >::back(), toy::FixedVector< type, allocatedSize >::back(), toy::FixedVector< type, allocatedSize >::back(), toy::FixedVector< type, allocatedSize >::begin(), toy::FixedVector< type, allocatedSize >::begin(), toy::CStringView::c_str(), toy::FixedString< allocatedSize >::c_str(), toy::CallbacksPool< type, allocatedSize >::call(), toy::CStringView::capacity(), toy::FixedString< allocatedSize >::capacity(), toy::FixedVector< type, allocatedSize >::capacity(), toy::FixedVector< type, allocatedSize >::cbegin(), toy::FixedVector< type, allocatedSize >::cend(), toy::CStringView::clear(), toy::FixedString< allocatedSize >::clear(), toy::FixedVector< type, allocatedSize >::clear(), toy::CStringView::compare(), toy::CStringView::compare(), toy::FixedString< allocatedSize >::compare(), toy::FixedString< allocatedSize >::compare(), toy::FixedString< allocatedSize >::compare(), toy::CStringView::contains(), toy::CStringView::contains(), toy::CStringView::contains(), toy::FixedString< allocatedSize >::contains(), toy::FixedString< allocatedSize >::contains(), toy::FixedString< allocatedSize >::contains(), toy::FixedString< allocatedSize >::contains(), toy::FixedString< allocatedSize >::copy(), toy::FixedVector< type, allocatedSize >::crbegin(), toy::FixedVector< type, allocatedSize >::crend(), toy::CStringView::data(), toy::FixedString< allocatedSize >::data(), toy::FixedString< allocatedSize >::data(), toy::FixedVector< type, allocatedSize >::data(), toy::FixedVector< type, allocatedSize >::data(), toy::CStringView::empty(), toy::FixedString< allocatedSize >::empty(), toy::FixedVector< type, allocatedSize >::empty(), toy::FixedVector< type, allocatedSize >::end(), toy::FixedVector< type, allocatedSize >::end(), toy::CStringView::ends_with(), toy::CStringView::ends_with(), toy::CStringView::ends_with(), toy::FixedString< allocatedSize >::ends_with(), toy::FixedString< allocatedSize >::ends_with(), toy::FixedString< allocatedSize >::ends_with(), toy::FixedString< allocatedSize >::ends_with(), toy::FixedString< allocatedSize >::erase(), toy::CStringView::find(), toy::CStringView::find(), toy::CStringView::find(), toy::FixedString< allocatedSize >::find(), toy::FixedString< allocatedSize >::find(), toy::FixedString< allocatedSize >::find(), toy::FixedString< allocatedSize >::find(), toy::CStringView::find_first_not_of(), toy::CStringView::find_first_not_of(), toy::CStringView::find_first_not_of(), toy::FixedString< allocatedSize >::find_first_not_of(), toy::FixedString< allocatedSize >::find_first_not_of(), toy::FixedString< allocatedSize >::find_first_not_of(), toy::FixedString< allocatedSize >::find_first_not_of(), toy::CStringView::find_first_of(), toy::CStringView::find_first_of(), toy::CStringView::find_first_of(), toy::FixedString< allocatedSize >::find_first_of(), toy::FixedString< allocatedSize >::find_first_of(), toy::FixedString< allocatedSize >::find_first_of(), toy::FixedString< allocatedSize >::find_first_of(), toy::CStringView::find_last_not_of(), toy::CStringView::find_last_not_of(), toy::CStringView::find_last_not_of(), toy::FixedString< allocatedSize >::find_last_not_of(), toy::FixedString< allocatedSize >::find_last_not_of(), toy::FixedString< allocatedSize >::find_last_not_of(), toy::FixedString< allocatedSize >::find_last_not_of(), toy::CStringView::find_last_of(), toy::CStringView::find_last_of(), toy::CStringView::find_last_of(), toy::FixedString< allocatedSize >::find_last_of(), toy::FixedString< allocatedSize >::find_last_of(), toy::FixedString< allocatedSize >::find_last_of(), toy::FixedString< allocatedSize >::find_last_of(), toy::CStringView::front(), toy::FixedString< allocatedSize >::front(), toy::FixedString< allocatedSize >::front(), toy::FixedVector< type, allocatedSize >::front(), toy::FixedVector< type, allocatedSize >::front(), toy::FixedString< allocatedSize >::insert(), toy::FixedString< allocatedSize >::insert(), toy::FixedString< allocatedSize >::insert(), toy::FixedString< allocatedSize >::insert(), toy::CStringView::length(), toy::FixedString< allocatedSize >::length(), toy::CStringView::max_size(), toy::FixedString< allocatedSize >::max_size(), toy::FixedVector< type, allocatedSize >::max_size(), toy::FixedString< allocatedSize >::operator+=(), toy::FixedString< allocatedSize >::operator+=(), toy::FixedString< allocatedSize >::operator+=(), toy::FixedString< allocatedSize >::operator+=(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), toy::CStringView::operator=(), toy::FixedString< allocatedSize >::operator=(), toy::FixedString< allocatedSize >::operator=(), toy::FixedString< allocatedSize >::operator=(), toy::FixedString< allocatedSize >::operator=(), toy::FixedVector< type, allocatedSize >::operator=(), toy::FixedVector< type, allocatedSize >::operator=(), toy::FixedVector< type, allocatedSize >::operator=(), toy::FixedVector< type, allocatedSize >::operator=(), toy::FixedVector< type, allocatedSize >::operator=(), toy::CStringView::operator[](), toy::FixedString< allocatedSize >::operator[](), toy::FixedString< allocatedSize >::operator[](), toy::FixedVector< type, allocatedSize >::operator[](), toy::FixedVector< type, allocatedSize >::operator[](), toy::FixedString< allocatedSize >::pop_back(), precision(), precision(), toy::FixedString< allocatedSize >::push_back(), toy::FixedVector< type, allocatedSize >::push_back(), put(), toy::FixedVector< type, allocatedSize >::rbegin(), toy::FixedVector< type, allocatedSize >::rbegin(), toy::CallbacksPool< type, allocatedSize >::remove(), toy::FixedVector< type, allocatedSize >::rend(), toy::FixedVector< type, allocatedSize >::rend(), toy::FixedString< allocatedSize >::replace(), toy::FixedString< allocatedSize >::replace(), toy::FixedString< allocatedSize >::replace(), toy::FixedString< allocatedSize >::replace(), toy::CallbacksPool< type, allocatedSize >::reset(), toy::CStringView::rfind(), toy::CStringView::rfind(), toy::CStringView::rfind(), toy::FixedString< allocatedSize >::rfind(), toy::FixedString< allocatedSize >::rfind(), toy::FixedString< allocatedSize >::rfind(), toy::FixedString< allocatedSize >::rfind(), toy::CStringView::size(), toy::FixedString< allocatedSize >::size(), toy::FixedVector< type, allocatedSize >::size(), toy::CStringView::starts_with(), toy::CStringView::starts_with(), toy::CStringView::starts_with(), toy::FixedString< allocatedSize >::starts_with(), toy::FixedString< allocatedSize >::starts_with(), toy::FixedString< allocatedSize >::starts_with(), toy::FixedString< allocatedSize >::starts_with(), str(), str(), toy::CallbacksPool< type, allocatedSize >::subscribersAmount(), toy::FixedString< allocatedSize >::substr(), toy::CStringView::swap(), toy::FixedString< allocatedSize >::swap(), swap(), tellp(), toy::FixedString< allocatedSize >::utf8_pop_back(), toy::CStringView::utf8_size(), toy::FixedString< allocatedSize >::utf8_size(), view(), and write().
operator<<() [6/17]
template<typename StringType> OStringStream< StringType > & toy::OStringStream< StringType >::operator<< (const void * value) constexpr noexcept
Inserts a pointer value into the stream.
This operator converts the pointer value to its hexadecimal string representation with "0x" prefix and appends it to the stream. The pointer is formatted as a hexadecimal number, matching the standard C++ pointer output format.
Parameters
value The pointer value to insert into the stream.
Returns
A reference to this OStringStream, allowing operator chaining.
Postcondition
The write position is advanced by the length of the appended string.
Note
This operator follows the same pattern as std::ostringstream::operator<<(const void*).
For null pointers, consider using operator<<(nullptr_t) for consistent "nullptr" output.
See also
operator<<(nullptr_t)
put(char_type)
tellp()
operator<<() [7/17]
template<typename StringType> OStringStream< StringType > & toy::OStringStream< StringType >::operator<< (double value) constexpr noexcept
Inserts a double-precision floating-point value into the stream.
This operator converts the double value to its decimal string representation with the current precision setting and appends it to the stream. The precision controls the number of digits displayed.
Parameters
value The double-precision floating-point value to insert into the stream.
Returns
A reference to this OStringStream, allowing operator chaining.
Postcondition
The write position is advanced by the length of the appended string.
Note
This operator follows the same pattern as std::ostringstream::operator<<(double).
The precision is controlled by precision(int) and defaults to 6 digits.
See also
precision() const
precision(int)
operator<<(float)
put(char_type)
tellp()
operator<<() [8/17]
template<typename StringType> OStringStream< StringType > & toy::OStringStream< StringType >::operator<< (float value) constexpr noexcept
Inserts a single-precision floating-point value into the stream.
This operator converts the float value to its decimal string representation with the current precision setting and appends it to the stream. The precision controls the number of digits displayed.
Parameters
value The single-precision floating-point value to insert into the stream.
Returns
A reference to this OStringStream, allowing operator chaining.
Postcondition
The write position is advanced by the length of the appended string.
Note
This operator follows the same pattern as std::ostringstream::operator<<(float).
The precision is controlled by precision() and defaults to 6 digits.
See also
precision() const
precision(int)
operator<<(double)
put(char_type)
tellp()
operator<<() [9/17]
template<typename StringType> OStringStream< StringType > & toy::OStringStream< StringType >::operator<< (int16_t value) constexpr noexcept
Inserts a signed 16-bit integer value into the stream.
This operator converts the signed 16-bit integer value to its decimal string representation and appends it to the stream. Negative values are prefixed with a minus sign.
Parameters
value The signed 16-bit integer value to insert into the stream.
Returns
A reference to this OStringStream, allowing operator chaining.
Postcondition
The write position is advanced by the length of the appended string.
Note
This operator follows the same pattern as std::ostringstream::operator<<(int16_t).
See also
operator<<(uint16_t)
put(char_type)
tellp()
operator<<() [10/17]
template<typename StringType> OStringStream< StringType > & toy::OStringStream< StringType >::operator<< (int32_t value) constexpr noexcept
Inserts a signed 32-bit integer value into the stream.
This operator converts the signed 32-bit integer value to its decimal string representation and appends it to the stream. Negative values are prefixed with a minus sign.
Parameters
value The signed 32-bit integer value to insert into the stream.
Returns
A reference to this OStringStream, allowing operator chaining.
Postcondition
The write position is advanced by the length of the appended string.
Note
This operator follows the same pattern as std::ostringstream::operator<<(int32_t).
See also
operator<<(uint32_t)
put(char_type)
tellp()
operator<<() [11/17]
template<typename StringType> OStringStream< StringType > & toy::OStringStream< StringType >::operator<< (int64_t value) constexpr noexcept
Inserts a signed 64-bit integer value into the stream.
This operator converts the signed 64-bit integer value to its decimal string representation and appends it to the stream. Negative values are prefixed with a minus sign.
Parameters
value The signed 64-bit integer value to insert into the stream.
Returns
A reference to this OStringStream, allowing operator chaining.
Postcondition
The write position is advanced by the length of the appended string.
Note
This operator follows the same pattern as std::ostringstream::operator<<(int64_t).
See also
operator<<(uint64_t)
put(char_type)
tellp()
operator<<() [12/17]
template<typename StringType> OStringStream< StringType > & toy::OStringStream< StringType >::operator<< (int8_t value) constexpr noexcept
Inserts a signed 8-bit integer value into the stream.
This operator converts the signed 8-bit integer value to its decimal string representation and appends it to the stream. Negative values are prefixed with a minus sign.
Parameters
value The signed 8-bit integer value to insert into the stream.
Returns
A reference to this OStringStream, allowing operator chaining.
Postcondition
The write position is advanced by the length of the appended string.
Note
This operator follows the same pattern as std::ostringstream::operator<<(int8_t).
See also
operator<<(uint8_t)
put(char_type)
tellp()
operator<<() [13/17]
template<typename StringType> OStringStream< StringType > & toy::OStringStream< StringType >::operator<< (nullptr_t) constexpr noexcept
Inserts a null pointer literal into the stream.
This operator inserts the string "nullptr" into the stream when a null pointer literal is provided. This provides a consistent and readable representation for null pointers.
Returns
A reference to this OStringStream, allowing operator chaining.
Postcondition
The write position is advanced by 7 characters (length of "nullptr").
Note
This operator follows the same pattern as std::ostringstream::operator<<(std::nullptr_t).
The output is always the string "nullptr", regardless of the actual null pointer value.
This operator is preferred over operator<<(const void*) for null pointer literals.
See also
operator<<(const void *)
put(char_type)
tellp()
operator<<() [14/17]
template<typename StringType> OStringStream< StringType > & toy::OStringStream< StringType >::operator<< (uint16_t value) constexpr noexcept
Inserts an unsigned 16-bit integer value into the stream.
This operator converts the unsigned 16-bit integer value to its decimal string representation and appends it to the stream.
Parameters
value The unsigned 16-bit integer value to insert into the stream.
Returns
A reference to this OStringStream, allowing operator chaining.
Postcondition
The write position is advanced by the length of the appended string.
Note
This operator follows the same pattern as std::ostringstream::operator<<(uint16_t).
See also
operator<<(int16_t)
put(char_type)
tellp()
operator<<() [15/17]
template<typename StringType> OStringStream< StringType > & toy::OStringStream< StringType >::operator<< (uint32_t value) constexpr noexcept
Inserts an unsigned 32-bit integer value into the stream.
This operator converts the unsigned 32-bit integer value to its decimal string representation and appends it to the stream.
Parameters
value The unsigned 32-bit integer value to insert into the stream.
Returns
A reference to this OStringStream, allowing operator chaining.
Postcondition
The write position is advanced by the length of the appended string.
Note
This operator follows the same pattern as std::ostringstream::operator<<(uint32_t).
See also
operator<<(int32_t)
put(char_type)
tellp()
operator<<() [16/17]
template<typename StringType> OStringStream< StringType > & toy::OStringStream< StringType >::operator<< (uint64_t value) constexpr noexcept
Inserts an unsigned 64-bit integer value into the stream.
This operator converts the unsigned 64-bit integer value to its decimal string representation and appends it to the stream.
Parameters
value The unsigned 64-bit integer value to insert into the stream.
Returns
A reference to this OStringStream, allowing operator chaining.
Postcondition
The write position is advanced by the length of the appended string.
Note
This operator follows the same pattern as std::ostringstream::operator<<(uint64_t).
See also
operator<<(int64_t)
put(char_type)
tellp()
operator<<() [17/17]
template<typename StringType> OStringStream< StringType > & toy::OStringStream< StringType >::operator<< (uint8_t value) constexpr noexcept
Inserts an unsigned 8-bit integer value into the stream.
This operator converts the unsigned 8-bit integer value to its decimal string representation and appends it to the stream.
Parameters
value The unsigned 8-bit integer value to insert into the stream.
Returns
A reference to this OStringStream, allowing operator chaining.
Postcondition
The write position is advanced by the length of the appended string.
Note
This operator follows the same pattern as std::ostringstream::operator<<(uint8_t).
See also
operator<<(int8_t)
put(char_type)
tellp()
operator=() [1/2]
template<typename StringType> OStringStream & toy::OStringStream< StringType >::operator= (const OStringStream< StringType > & other) constexpr default noexcept
Copy assignment operator.
Assigns the contents of another OStringStream to this stream. The assignment performs a deep copy of the underlying string.
Parameters
other The source OStringStream to copy from.
Returns
A reference to this OStringStream after assignment.
Precondition
The other stream must be valid and properly initialized.
Postcondition
This stream contains the same content as the source other stream.
The underlying string is a copy of the source string.
Note
Self-assignment is handled correctly and safely.
operator=() [2/2]
template<typename StringType> OStringStream & toy::OStringStream< StringType >::operator= (OStringStream< StringType > && other) constexpr default noexcept
Move assignment operator.
Assigns the contents of another OStringStream to this stream using move semantics. The source stream is left in a valid but unspecified state.
Parameters
other The source OStringStream to move from.
Returns
A reference to this OStringStream after assignment.
Precondition
The other stream must be valid and properly initialized.
Postcondition
This stream contains the same content as the source other stream.
The source other stream is left in a valid but unspecified state.
Note
Self-assignment is handled correctly and safely.
precision() [1/2]
template<typename StringType> int toy::OStringStream< StringType >::precision () const nodiscard constexpr noexcept
Returns the current floating-point precision setting.
This method returns the precision value that will be used for formatting floating-point numbers when writing to the stream. The precision specifies the number of digits to display.
Returns
The current precision value.
Note
The precision value affects how floating-point numbers are formatted when written to the stream.
See also
precision(int)
precision() [2/2]
template<typename StringType> int toy::OStringStream< StringType >::precision (int newPrecision) constexpr noexcept
Sets the floating-point precision and returns the previous value.
This method sets the precision value that will be used for formatting floating-point numbers when writing to the stream. The precision specifies the number of digits to display.
Parameters
newPrecision The new precision value to set.
Returns
The previous precision value before the change.
Precondition
The newPrecision must be non-negative.
Note
The precision value affects how floating-point numbers are formatted when written to the stream.
See also
precision() const
put()
template<typename StringType> OStringStream< StringType > & toy::OStringStream< StringType >::put (char_type character) constexpr noexcept
Appends a single character to the end of the stream.
This method appends the specified character to the end of the underlying string storage. The character is added to the current content without replacing it.
Parameters
character The character to append to the stream.
Returns
A reference to this OStringStream, allowing method chaining.
Precondition
The character must not be the null character ('\0').
Postcondition
The character is appended to the end of the stream content.
The write position is advanced by one character.
See also
write(const char_type *, size_t)
tellp()
str() [1/2]
template<typename StringType> const StringType & toy::OStringStream< StringType >::str () const nodiscard constexpr noexcept
Returns a const reference to the underlying string.
This method provides read-only access to the internal string storage.
Returns
A const reference to the underlying string.
Note
The returned reference is valid for the lifetime of the OStringStream object.
See also
view()
str() [2/2]
template<typename StringType> template<StringLike SourceStringType> void toy::OStringStream< StringType >::str (const SourceStringType & string) constexpr noexcept
Sets the content of the stream from a string-like object.
This method replaces the current content of the stream with the content from a string-like object.
Template Parameters
SourceStringType The type of the source string. Must satisfy the toy::StringLike concept.
Parameters
string The source string-like object to set the content from.
Precondition
The string must be valid and properly initialized.
Postcondition
The stream contains a copy of the source string content.
The previous content of the stream is replaced.
Note
The method performs a deep copy of the string content.
The source string type can be different from StringType as long as both satisfy toy::StringLike.
This method provides a convenient way to update the stream content after construction.
See also
str() const
swap()
template<typename StringType> void toy::OStringStream< StringType >::swap (OStringStream< StringType > & other) constexpr noexcept
Swaps the contents of this stream with another stream.
This method exchanges the underlying string storage between this stream and the other stream. Both streams must have the same StringType template parameter.
Parameters
other The stream to swap contents with.
Postcondition
The contents of this stream and other are exchanged.
Both streams remain valid after the swap operation.
Note
Self-swap is safe and has no effect.
The operation is noexcept and provides strong exception guarantee.
This method is useful for efficient content exchange without copying.
tellp()
template<typename StringType> OStringStream< StringType >::pos_type toy::OStringStream< StringType >::tellp () const nodiscard constexpr noexcept
Returns the current write position in the stream.
This method returns the position where the next write operation will append data. Since OStringStream only supports appending operations (all writes go to the end), the write position always equals the number of characters currently in the stream, which is the same as the size of the underlying string.
Returns
The current write position, representing the index where the next character will be appended. This value is always equal to the number of characters written so far and to str().size().
Note
Since all operations append to the end, the write position is always equal to the stream size.
See also
str() const
put(char_type)
write(const char_type *, size_t)
view()
template<typename StringType> CStringView toy::OStringStream< StringType >::view () const nodiscard constexpr noexcept
Returns a non-owning view of the underlying string.
This method creates and returns a toy::CStringView that provides read-only access to the underlying string storage without copying the content. The view is lightweight and does not own the string data.
Returns
A toy::CStringView representing the current content of the stream.
Note
The returned view is valid for the lifetime of the OStringStream object.
The view does not own the string data and should not be used after the OStringStream is destroyed.
This method is useful for passing the stream content to functions that accept toy::CStringView without creating a copy.
The view reflects the current state of the stream at the time of the call.
See also
str() const
toy::CStringView
write()
template<typename StringType> OStringStream< StringType > & toy::OStringStream< StringType >::write (const char_type * string, size_t count) constexpr noexcept
Writes a specified number of characters from a buffer to the stream.
This method appends count characters from the buffer pointed to by string to the end of the stream. The characters are copied directly from the buffer without requiring null termination.
Parameters
string The pointer to the character buffer to write from. Must not be null if count is greater than zero.
count The number of characters to write from the buffer.
Returns
A reference to this OStringStream, allowing method chaining.
Precondition
If count is greater than zero, string must not be null and must point to a valid buffer of at least count characters.
All characters in the buffer must not be null characters ('\0').
Postcondition
count characters from the buffer are appended to the end of the stream content.
The write position is advanced by count characters.
Note
This method is useful for writing binary data or partial strings that may not be null-terminated.
If count is zero, the method returns without modifying the stream.
See also
put(char_type)
tellp()
Member Data Documentation
_precision
template<typename StringType> int toy::OStringStream< StringType >::_precision = 6 private
Floating-point precision value used for number formatting.
_string
template<typename StringType> StringType toy::OStringStream< StringType >::_string private
Internal string storage for the stream content.
The documentation for this class was generated from the following files:
include/core/o_string_stream.hpp
include/core/o_string_stream.inl