ToyGine2: anonymous_namespace{utils.cpp} Namespace Reference
anonymous_namespace{utils.cpp} Namespace Reference
Classes
struct divmod10
Functions
constexpr divmod10 divModU10 (std::uint32_t value) noexcept
Divides a given 32-bit unsigned integer by 10 and returns the quotient and remainder.
constexpr std::int32_t ftoa32Engine (char *buffer, float value, std::size_t precision) noexcept
Converts a floating-point number to its string representation in a specified precision.
constexpr std::int32_t ftoa64Engine (char *buffer, double value, std::size_t precision) noexcept
Converts a 64-bit floating-point number to its string representation with specified precision.
void floatPostProcess (char *dest, char *srcBuffer, std::size_t bufferSize, std::int32_t exp10, std::size_t precision) noexcept
Processes a string representation of a floating-point number, adjusting the exponent, and stripping trailing zeros.
Variables
constexpr std::array< std::uint8_t, 256 > sc_utf8CharSizeTable
constexpr std::array< std::uint32_t, 32 > sc_exponentTable
Function Documentation
divModU10()
divmod10 anonymous_namespace{utils.cpp}::divModU10 (std::uint32_t value) constexpr noexcept
Divides a given 32-bit unsigned integer by 10 and returns the quotient and remainder.
The function approximates division by 10 using a sequence of shift-and-add operations to compute the quotient, then derives the remainder and corrects it if needed. It returns both quotient and remainder.
Parameters
value The 32-bit unsigned integer to divide by 10.
Returns
A struct containing the quotient and remainder of the division.
{
  divmod10 res;
  res.quot = value >> 1;
  res.quot += res.quot >> 1;
  res.quot += res.quot >> 4;
  res.quot += res.quot >> 8;
  res.quot += res.quot >> 16;
  const auto qq = res.quot;
  res.quot >>= 3;
  constexpr std::uint32_t mask32 = 0xFFFFFFF8;
  res.rem = static_cast<std::uint8_t>(value - ((res.quot << 1) + (qq & mask32)));
  if (res.rem > 9) {
    res.rem -= 10;
    ++res.quot;
  }
  return res;
}
Referenced by floatPostProcess().
floatPostProcess()
void anonymous_namespace{utils.cpp}::floatPostProcess (char * dest, char * srcBuffer, std::size_t bufferSize, std::int32_t exp10, std::size_t precision) noexcept
Processes a string representation of a floating-point number, adjusting the exponent, and stripping trailing zeros.
This function processes a string representation of a floating-point number, adjusting the exponent according to the given precision, and stripping trailing zeros. The function also handles the case of negative zero.
Parameters
dest The destination buffer where the processed string is stored.
srcBuffer The source buffer containing the string representation of a floating-point number.
bufferSize The size of the source buffer.
exp10 The exponent of the floating-point number in the given precision.
precision The number of decimal places to include in the representation.
Note
The function assumes that the destination buffer is large enough to hold the processed string. The buffer will contain the string representation in the form "+d.dd...e±dd" for normalized numbers.
{
  char const * strBegin = &srcBuffer[2];
  if (srcBuffer[1] != '0') {
    // Carry propagated into the integer position at [1] (e.g., 0.999.. -> 1.000..).
    // Include that '1' in the mantissa by shifting strBegin left, and bump exp10 to keep
    // the mantissa/exponent product invariant.
    ++exp10;
    --strBegin;
  }
  const auto digits = std::strlen(strBegin);
  std::size_t intDigits = 0;
  std::size_t leadingZeros = 0;
  if (static_cast<std::size_t>(std::abs(exp10)) >= precision) {
    intDigits = 1;
  } else if (exp10 >= 0) {
    intDigits = static_cast<std::size_t>(exp10 + 1);
    exp10 = 0;
  } else {
    intDigits = 0;
    leadingZeros = static_cast<std::size_t>(-exp10 - 1);
    exp10 = 0;
  }
  char * outputPointer = dest;
  if (*srcBuffer == '-') // copy sign if negative
    *outputPointer++ = '-';
  std::size_t fractionDigits = digits > intDigits ? digits - intDigits : 0;
  if (intDigits > 0) {
    auto count = std::min(intDigits, digits);
    while (count--)
      *outputPointer++ = *strBegin++;
    auto trailingZeros = static_cast<std::int32_t>(intDigits) - static_cast<std::int32_t>(digits);
    while (trailingZeros-- > 0)
      *outputPointer++ = '0';
  } else {
    *outputPointer++ = '0';
  }
  if (fractionDigits > 0) {
    *outputPointer++ = '.';
    while (leadingZeros-- > 0)
      *outputPointer++ = '0';
    while (fractionDigits-- > 0)
      *outputPointer++ = *strBegin++;
  }
  if (exp10 != 0) {
    *outputPointer++ = 'e';
    std::uint32_t upow10;
    if (exp10 < 0) {
      *outputPointer++ = '-';
      upow10 = static_cast<std::uint32_t>(-exp10);
    } else {
      *outputPointer++ = '+';
      upow10 = static_cast<std::uint32_t>(exp10);
    }
    char * bufferEndPointer = srcBuffer + bufferSize - 1;
    *bufferEndPointer = '\0';
    divmod10 res;
    res.quot = upow10;
    do {
      res = divModU10(res.quot);
      *--bufferEndPointer = res.rem + '0';
    } while (res.quot != 0);
    while (bufferEndPointer < srcBuffer + bufferSize)
      *outputPointer++ = *bufferEndPointer++;
  }
  *outputPointer = '\0';
}
Referenced by toygine::ftoa(), and toygine::ftoa().
ftoa32Engine()
std::int32_t anonymous_namespace{utils.cpp}::ftoa32Engine (char * buffer, float value, std::size_t precision) constexpr noexcept
Converts a floating-point number to its string representation in a specified precision.
The output is always sign-prefixed ('+' or '-') and normalized as "+0.<digits>" or "-0.<digits>".
This function converts a given floating-point number into its string representation, storing the result in the provided destination buffer. The function rounds the result to the given precision and stores the exponent in the return value.
Parameters
value The floating-point number to be converted.
buffer The destination buffer where the converted string is stored.
precision The precision (digits after the decimal point). For IEEE-754 f32, practical precision is ~7–9 digits.
Returns
The exponent of the converted number in the given precision. Returns 0xFF for zero, subnormals (unsupported), NaN, and INF.
Note
The function assumes that the destination buffer is large enough to hold the converted string. The function does not support subnormals.
{
  const auto uvalue = std::bit_cast<uint32_t>(value);
  const auto exponent = static_cast<std::uint8_t>(uvalue >> 23);
  if (exponent == 0) { // don't care about a subnormals
    buffer[0] = '0';
    buffer[1] = '\0';
    return 0xFF;
  }
  char * pointer = buffer;
  if (uvalue & 0x80000000)
    *pointer++ = '-';
  else
    *pointer++ = '+';
  const std::uint32_t fraction = (uvalue & 0x007FFFFF) | 0x00800000;
  if (exponent == 0xFF) {
    if (fraction & 0x007FFFFF) {
      pointer[0] = 'N';
      pointer[1] = 'A';
      pointer[2] = 'N';
    } else {
      pointer[0] = 'I';
      pointer[1] = 'N';
      pointer[2] = 'F';
    }
    pointer[3] = '\0';
    return 0xFF;
  }
  *pointer++ = '0';
  std::int32_t exp10 = (((exponent >> 3) * 77 + 63) >> 5) - 38;
  std::uint32_t t
    = static_cast<std::uint32_t>((static_cast<std::uint64_t>(fraction << 8) * sc_exponentTable[exponent / 8U]) >> 32)
      + 1;
  t >>= (7 - (exponent & 7));
  std::uint8_t digit = t >> 28;
  while (digit == 0) {
    t &= 0x0fffffff;
    t *= 10;
    digit = t >> 28;
    --exp10;
  }
  for (std::size_t iter = precision + 1; iter > 0; --iter) {
    digit = t >> 28;
    *pointer++ = digit + '0';
    t &= 0x0fffffff;
    t *= 10;
  }
  // roundup
  if (buffer[precision + 2] >= '5')
    buffer[precision + 1]++;
  pointer[-1] = '\0';
  pointer -= 2;
  for (std::size_t index = precision + 1; index > 1; --index) {
    if (buffer[index] > '9') {
      buffer[index] -= 10;
      ++buffer[index - 1];
    }
  }
  // If carry propagated into the integer digit ('0' at buffer[1]), adjust it and bump the exponent.
  if (buffer[1] > '9') {
    buffer[1] = '1';
    ++exp10;
  }
  while (pointer > buffer + 1 && pointer[0] == '0')
    *pointer-- = '\0';
  return exp10;
}
Referenced by toygine::ftoa(), and ftoa64Engine().
ftoa64Engine()
std::int32_t anonymous_namespace{utils.cpp}::ftoa64Engine (char * buffer, double value, std::size_t precision) constexpr noexcept
Converts a 64-bit floating-point number to its string representation with specified precision.
The output is always sign-prefixed ('+' or '-') and normalized as "+0.<digits>" or "-0.<digits>".
This function converts a given 64-bit floating-point number into its string representation, storing the result in the provided buffer. The conversion includes handling special cases such as subnormals, NaN, and infinity. The output is formatted according to the specified precision.
Parameters
buffer The destination buffer where the converted string is stored.
value The 64-bit floating-point number to be converted.
precision The number of decimal places to include in the representation.
Returns
The exponent of the converted number in the given precision. Returns 0x7FF for zero, subnormals (unsupported), NaN, and INF.
Note
The function assumes that the buffer is large enough to hold the converted string. The buffer will contain the string representation in the form "+d.dd...e±dd" for normalized numbers.
{
  const auto uvalue = std::bit_cast<uint64_t>(value);
  const auto exponent = static_cast<std::uint32_t>(uvalue >> 52) & 0x07FF;
  if (exponent == 0) { // don't care about a subnormals
    buffer[0] = '0';
    buffer[1] = '\0';
    return 0x7FF;
  }
  if (exponent == 0x07FF) {
    char * pointer = buffer;
    if (uvalue & 0x8000000000000000ULL)
      *pointer++ = '-';
    else
      *pointer++ = '+';
    const std::uint64_t fraction = (uvalue & 0x001FFFFFFFFFFFFFULL) | 0x0010000000000000ULL;
    if (fraction & 0x000FFFFFFFFFFFFFULL) {
      pointer[0] = 'N';
      pointer[1] = 'A';
      pointer[2] = 'N';
    } else {
      pointer[0] = 'I';
      pointer[1] = 'N';
      pointer[2] = 'F';
    }
    pointer[3] = '\0';
    return 0x7FF;
  }
  return ftoa32Engine(buffer, static_cast<float>(value), precision);
}
Referenced by toygine::ftoa().
Variable Documentation
sc_exponentTable
std::array<std::uint32_t, 32> anonymous_namespace{utils.cpp}::sc_exponentTable constexpr
Initial value:
{
  {0xF0BDC21A, 0x3DA137D5, 0x9DC5ADA8, 0x2863C1F5, 0x6765C793, 0x1A784379, 0x43C33C19, 0xAD78EBC5,
   0x2C68AF0B, 0x71AFD498, 0x1D1A94A2, 0x4A817C80, 0xBEBC2000, 0x30D40000, 0x7D000000, 0x20000000,
   0x51EB851E, 0xD1B71758, 0x35AFE535, 0x89705F41, 0x232F3302, 0x5A126E1A, 0xE69594BE, 0x3B07929F,
   0x971DA050, 0x26AF8533, 0x63090312, 0xFD87B5F2, 0x40E75996, 0xA6274BBD, 0x2A890926, 0x6CE3EE76}}
{
  {0xF0BDC21A, 0x3DA137D5, 0x9DC5ADA8, 0x2863C1F5, 0x6765C793, 0x1A784379, 0x43C33C19, 0xAD78EBC5,
   0x2C68AF0B, 0x71AFD498, 0x1D1A94A2, 0x4A817C80, 0xBEBC2000, 0x30D40000, 0x7D000000, 0x20000000,
   0x51EB851E, 0xD1B71758, 0x35AFE535, 0x89705F41, 0x232F3302, 0x5A126E1A, 0xE69594BE, 0x3B07929F,
   0x971DA050, 0x26AF8533, 0x63090312, 0xFD87B5F2, 0x40E75996, 0xA6274BBD, 0x2A890926, 0x6CE3EE76}};
sc_utf8CharSizeTable
std::array<std::uint8_t, 256> anonymous_namespace{utils.cpp}::sc_utf8CharSizeTable constexpr
Initial value:
{
  {0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01,
   0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01,
   0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01,
   0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01,
   0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01,
   0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01,
   0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01,
   0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
   0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
   0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
   0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
   0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02,
   0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02,
   0x03, 0x03, 0x03, 0x03, 0x03, 0x03, 0x03, 0x03, 0x03, 0x03, 0x03, 0x03, 0x03, 0x03, 0x03, 0x03,
   0x04, 0x04, 0x04, 0x04, 0x04, 0x04, 0x04, 0x04, 0x05, 0x05, 0x05, 0x05, 0x06, 0x06, 0x07, 0x08}}
{
  {0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01,
   0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01,
   0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01,
   0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01,
   0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01,
   0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01,
   0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01,
   0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
   0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
   0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
   0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
   0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02,
   0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02,
   0x03, 0x03, 0x03, 0x03, 0x03, 0x03, 0x03, 0x03, 0x03, 0x03, 0x03, 0x03, 0x03, 0x03, 0x03, 0x03,
   0x04, 0x04, 0x04, 0x04, 0x04, 0x04, 0x04, 0x04, 0x05, 0x05, 0x05, 0x05, 0x06, 0x06, 0x07, 0x08}};