name: CMake

on:
  workflow_call:

permissions: {}

jobs:
  cmake:
    strategy:
      matrix:
        include:
          - name: Linux Ninja
            os: ubuntu-latest
            run_test: "true"
            cmake_preset: linux-ninja-release

          - name: Linux Ninja with coverage
            os: ubuntu-latest
            run_test: "true"
            run_test_with_coverage: "true"
            cmake_preset: linux-ninja-debug

          - name: macOS XCode
            os: macos-15
            run_test: "true"
            cmake_preset: macos-xcode

          - name: macOS Ninja
            os: macos-15
            run_test: "true"
            cmake_preset: macos-ninja-release
            cpack_type: RelWithDebInfo
            cpack_extension: tar.gz

          - name: Windows MSVC
            os: windows-2025
            cmake_preset: windows-msvc

          - name: Windows MSVC x86
            os: windows-2025
            cmake_preset: windows-msvc-x86

    name: CMake (${{ matrix.name }})
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          submodules: recursive

      - name: Prepare CI
        run: |
          if [[ "${{ matrix.os }}" =~ "windows" ]]; then
            MSVC_INSTALL_PATH=$(vswhere -latest -property installationPath)
            echo "MSVC_INSTALL_PATH = $MSVC_INSTALL_PATH"

            echo "Installed toolset versions:"
            ls -vr "$MSVC_INSTALL_PATH/VC/Tools/MSVC"

            TOOLS_DIR=$(ls -vr "$MSVC_INSTALL_PATH/VC/Tools/MSVC/" | head -1)
            echo "TOOLS_DIR = $TOOLS_DIR"

            DUMPBIN_PATH="$MSVC_INSTALL_PATH/VC/Tools/MSVC/$TOOLS_DIR/bin/Hostx64/x64/dumpbin.exe"
            echo "DUMPBIN_PATH = $DUMPBIN_PATH"
          elif [[ "${{ matrix.os }}" =~ "macos" ]]; then
            # Prefer the desired version if it exists, otherwise keep the default.
            if [ -d "/Applications/Xcode_16.4.app" ]; then
              sudo xcode-select -s /Applications/Xcode_16.4.app
            fi
          elif [[ "${{ matrix.os }}" =~ "ubuntu" ]]; then
            sudo apt-get update -qq
            sudo apt-get install -y gcc-14 g++-14
            sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-14 100
            sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-14 100
          fi

      - name: Configure
        run: |
          cmake -DTOYGINE_BUILD_TESTS=$([ "${{ matrix.run_test }}" = "true" ] && echo ON || echo OFF) -DTOYGINE_TEST_WITH_COVERAGE=$([ "${{ matrix.run_test_with_coverage }}" = "true" ] && echo ON || echo OFF) --preset ${{ matrix.cmake_preset }}

      - name: Build
        run: |
          cmake --build --preset ${{ matrix.cmake_preset }}

      - name: Test
        if: ${{ matrix.run_test }}
        continue-on-error: true
        run: |
          ctest --preset ${{ matrix.cmake_preset }}
