name: Pull Request

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  security-events: write

jobs:
  dispatcher:
    name: Job dispatcher
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        shell: bash
    outputs:
      runCxxAnalyzers: ${{ steps.dispatch.outputs.runCxxAnalyzers }}
    steps:
      - uses: actions/github-script@v7.0.1
        id: dispatch
        with:
          script: |
            for await (const modifiedFiles of github.paginate.iterator(
                github.rest.pulls.listFiles, {
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    pull_number: ${{ github.event.number }},
                }
            )) {
                if (modifiedFiles.data.some((fileMetadata) =>
                    [/\.c$/, /\.cpp$/, /\.h$/, /\.hpp$/, /\.inl$/, /CMakeLists\.txt$/].some((pattern) => pattern.test(fileMetadata.filename))
                )) {
                    core.setOutput("runCxxAnalyzers", "YES");
                    break;
                }
            }

  style:
    name: Code style check
    needs:
      - dispatcher
    uses: ./.github/workflows/code_style_check.yaml
    secrets: inherit

  security_check:
    name: Codacy Security Analysis
    needs:
      - dispatcher
    uses: ./.github/workflows/codacy-security-analysis.yaml
    secrets: inherit

  build:
    name: Build using CMake
    needs:
      - style
      - security_check
    uses: ./.github/workflows/build_cmake.yaml
    secrets: inherit
