name: Push

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: read

jobs:
  quality:
    name: Check code quality
    permissions:
      contents: read
      pull-requests: read
      security-events: write
    uses: ./.github/workflows/check_code_quality.yaml

  build:
    name: Build using CMake
    permissions:
      contents: read
      packages: read
      checks: write
    uses: ./.github/workflows/build_cmake.yaml
    secrets: inherit
