name: Push

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  id-token: write
  pages: write
  pull-requests: write

jobs:
  build:
    name: Build using CMake
    uses: ./.github/workflows/build_cmake.yaml
